Nvl\Cms\Domain\Model\Post\PostType:
  type: embededDocument
  name: 
    type: string

Nvl\Cms\Domain\Model\Post\Post:
  type: document
  collection: posts
  customId: true
  #embedOne:
    #type:
      #targetDocument: Nvl\Cms\Domain\Model\Post\PostType
  fields:
    id: 
      id: true
      strategy: INCREMENT
    title: 
      type: string
    displayContent:
      type: string
    originalContent:
      type: string
    author:
      type: string
    createdDate:
      type: timestamp
    modifiedDate:
      type: timestamp
    tags:
      type: hash
    status:
      type: string
    commentCount:
      type: int
    likeCount:
      type: int
    sticky:
      type: boolean