Nvl\Cms\Domain\Model\Post\Post:
  type: document
  collection: posts
  customId: true
  embedOne:
    content:
      targetDocument: Nvl\Cms\Domain\Model\Post\PostContent
    meta:
      targetDocument: Nvl\Cms\Domain\Model\Post\PostMeta
  referenceOne:
    author:
      targetDocument: Nvl\Cms\Domain\Model\User\User
  fields:
    id: 
      id: true
      strategy: AUTO
    createdDate:
      type: timestamp
    modifiedDate:
      type: timestamp
    publishedDate:
      type: timestamp
    status:
      type: string
    version:
      type: int 
      lock: true
