Nvl\Cms\Domain\Model\User\User:
  type: document
  collection: users
  customId: true
  embedOne:
    loginInfo:
      targetDocument: Nvl\Cms\Domain\Model\User\Login
    contact:
      targetDocument: Nvl\Cms\Domain\Model\User\ContactInfo
    stats:
      targetDocument: Nvl\Cms\Domain\Model\User\UserStats
  fields:
    id: 
      id: true
      strategy: AUTO
    confirmed: 
      type: boolean
    status:
      type: string
    publishedPostCount:
      type: int
    postCount:
      type: int
    likeCount:
      type: int
    lastLogin:
      type: timestamp
    createdDate:
      type: timestamp
    modifiedDate:
      type: timestamp