Nvl\Cms\Domain\Model\Post\PostMeta:
  type: embeddedDocument
  fields:
    tags: 
      type: collection
    commentCount:
      type: int
    likeCount:
      type: int
    sticky:
      type: boolean
