Nvl\Cms\Domain\Model\Post\Post:
  type: document
  collection: posts
  customId: true
  embedOne:
    content:
      targetDocument: Nvl\Cms\Domain\Model\Post\PostContent
    meta:
      targetDocument: Nvl\Cms\Domain\Model\Post\PostMeta
  fields:
    id: 
      id: true
      strategy: INCREMENT
    author:
      type: string
    createdDate:
      type: timestamp
    modifiedDate:
      type: timestamp
    status:
      type: string
